import assert from 'node:assert/strict';
import test from 'node:test';
import jevSort, { bitonicSort, quickSort, scoreSort, bitonicNetwork, createJevClient, paddedSize } from '../dist/index.js';
import quickSortSubpath from '../dist/quicksort.js';
import bitonicSortSubpath from '../dist/bitonic.js';

const numericComparator=async pairs=>Object.fromEntries(pairs.map(pair=>[pair.id,pair.left<=pair.right?'left':'right']));

test('root default is the Score sorter',()=>{assert.equal(jevSort,scoreSort);assert.equal(quickSort,quickSortSubpath);assert.equal(bitonicSort,bitonicSortSubpath)});
test('calculates power-of-two padding',()=>{assert.equal(paddedSize(0),1);assert.equal(paddedSize(5),8);assert.equal(paddedSize(100),128);assert.throws(()=>paddedSize(-1),/non-negative/)});
test('builds the expected fixed bitonic network',()=>{const network=bitonicNetwork(8);assert.equal(network.length,6);assert.deepEqual(network.map(w=>w.length),[4,4,4,4,4,4]);assert.throws(()=>bitonicNetwork(7),/power of two/)});
test('bitonic sorts an unpadded list',async()=>{const r=await bitonicSort([7,1,9,2,5],numericComparator);assert.deepEqual(r.items,[1,2,5,7,9]);assert.equal(r.stats.algorithm,'bitonic');assert.equal(r.stats.paddedSize,8)});
test('named low-level quicksort sorts and uses fewer comparisons',async()=>{const values=[12,3,18,1,7,14,5,9,2,16,11,4,20,8,6,19,10,15,13,17],q=await quickSort(values,numericComparator),b=await bitonicSort(values,numericComparator);assert.deepEqual(q.items,[...values].sort((a,b)=>a-b));assert.ok(q.stats.comparisons<b.stats.comparisons)});
test('quicksort advances all active partitions in parallel',async()=>{const waves=[],r=await quickSort([8,7,6,5,4,3,2,1],async(p,c)=>{waves.push(c.wave);return numericComparator(p)});assert.deepEqual(r.items,[1,2,3,4,5,6,7,8]);assert.equal(waves.length,r.stats.waves)});
test('runs chunks in the same bitonic wave concurrently',async()=>{let active=0,max=0;const r=await bitonicSort([8,7,6,5,4,3,2,1],async p=>{active++;max=Math.max(max,active);await new Promise(x=>setTimeout(x,15));active--;return numericComparator(p)},{maxBatchSize:2});assert.deepEqual(r.items,[1,2,3,4,5,6,7,8]);assert.equal(max,2);assert.equal(r.stats.batchCalls,12)});
test('validates pivot selection',async()=>{await assert.rejects(quickSort([2,1],numericComparator,{choosePivot:()=>5}),/valid partition index/)});
test('rejects malformed pairwise answers',async()=>{await assert.rejects(quickSort([2,1],async()=>({})),/must return "left" or "right"/);await assert.rejects(bitonicSort([2,1],async()=>({})),/must return "left" or "right"/)});

test('score sort batches, runs concurrently, and keeps stable ties',async()=>{let active=0,max=0;const r=await scoreSort(Array.from({length:1000},(_,i)=>i),async entries=>{active++;max=Math.max(max,active);await new Promise(x=>setTimeout(x,5));active--;return Object.fromEntries(entries.map(e=>[e.id,{score:e.item%10}]))},{maxBatchSize:350,concurrency:4});assert.equal(r.items.length,1000);assert.deepEqual(r.items.slice(0,3),[9,19,29]);assert.equal(r.stats.judgments,1000);assert.equal(r.stats.batchCalls,3);assert.equal(max,3)});
test('score sort rejects malformed scores and options',async()=>{await assert.rejects(scoreSort([1],async()=>({})),/invalid score/);await assert.rejects(scoreSort([1],async()=>({i0:{score:1}}),{concurrency:0}),/concurrency/)});

test('jev client defaults to Score and preserves explicit pairwise methods',async()=>{const original=globalThis.fetch,requests=[];globalThis.fetch=async(url,init)=>{assert.equal(init.headers.Authorization,'Bearer secret');assert.match(String(url),/\/v1\/systemone$/);const body=JSON.parse(init.body);requests.push(body);const answers=Object.fromEntries(Object.entries(body.questions).map(([id,q])=>{if(q.type==='score')return[id,{type:'score',score:5-Number(q.instructions.item.value),confidence:.9,probabilities:[0,0,1,0,0]}];const p=body.state.pairs[id];return[id,{type:'choice',choice:p.item_a.value<=p.item_b.value?'left':'right',confidence:.9,probabilities:{left:.9,right:.1}}]}));return new Response(JSON.stringify({model:'jev-test',answers,usage:{input_tokens:1,output_tokens:1}}),{status:200,headers:{'content-type':'application/json'}})};try{const client=createJevClient({apiKey:'secret'}),values=[{value:4},{value:1},{value:3},{value:2}],scored=await client.jevSort(values,'smallest first'),quick=await client.quickSort(values,'smallest first'),bitonic=await client.bitonicSort(values,'smallest first');assert.deepEqual(scored.items.map(x=>x.value),[1,2,3,4]);assert.equal(scored.stats.algorithm,'score');assert.equal(scored.stats.judgments,4);assert.deepEqual(quick.items.map(x=>x.value),[1,2,3,4]);assert.deepEqual(bitonic.items.map(x=>x.value),[1,2,3,4]);assert.ok(requests.some(b=>Object.values(b.questions)[0].type==='score'));assert.ok(requests.some(b=>Object.values(b.questions)[0].type==='choice'))}finally{globalThis.fetch=original}});
test('jev client validates Score responses and criteria',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({model:'jev-test',answers:{},usage:{input_tokens:1,output_tokens:1}}),{status:200,headers:{'content-type':'application/json'}});try{const client=createJevClient({apiKey:'x'});await assert.rejects(client.jevSort([2,1],'smallest first'),/invalid score/);await assert.rejects(client.jevSort([2,1],'smallest first',{criteria:['one']}),/at least two/)}finally{globalThis.fetch=original}});
test('honors an aborted signal',async()=>{const controller=new AbortController();controller.abort(new Error('stopped'));await assert.rejects(quickSort([2,1],numericComparator,{signal:controller.signal}),/stopped/);await assert.rejects(jevSort([2,1],async()=>({}),{signal:controller.signal}),/stopped/)});
